language: android

git:
  depth: 3

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew clean test assembleDebug -i