language: android

git:
  depth: 3

jdk:
  - oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean test assembleDebug